### ISSUE TITLE
c=Cannot build openssh

### ISSUE THREAD

**Issue by amal-khailtash** [Infinidat/relocatable-python#5]
$ ./bin/build
...
(umask 022 ; ./mkinstalldirs /var/empty)
mkdir /var/empty
mkdir: cannot create directory ‘/var/empty’: Permission denied
Makefile:253: recipe for target 'install-files' failed
make: *** [install-files] Error 1
openssh: Command failed with exit code 2: make  install
openssh: Compilation error. The package is left as is at /home/username/relocatable-python/parts/openssh__compile__/openssh-5.8p1 where you can inspect what went wrong
While:
  Installing openssh.
Error: System error

**Comment by wiggin15** [comment]
I committed a fix but I still need to make sure it doesn't break anything on any of the supported platforms. Please let me know if it fixes your issue.

**Comment by amal-khailtash** [comment]
Similar error and the same for python3 version.  This one is on Ubuntu 14.10.

(cd openbsd-compat && make)
make[1]: Entering directory '/home/username/relocatable-python/parts/openssh__compile__/openssh-5.8p1/openbsd-compat'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/username/relocatable-python/parts/openssh__compile__/openssh-5.8p1/openbsd-compat'
./mkinstalldirs /home/username/relocatable-python/dist/bin
./mkinstalldirs /home/username/relocatable-python/dist/sbin
./mkinstalldirs /home/username/relocatable-python/dist/share/man
./mkinstalldirs /home/username/relocatable-python/dist/share/man/man1
./mkinstalldirs /home/username/relocatable-python/dist/share/man/man5
./mkinstalldirs /home/username/relocatable-python/dist/share/man/man8
./mkinstalldirs /home/username/relocatable-python/dist/libexec
(umask 022 ; ./mkinstalldirs /var/empty)
mkdir /var/empty
mkdir: cannot create directory ‘/var/empty’: Permission denied
Makefile:253: recipe for target 'install-files' failed
make: *** [install-files] Error 1
openssh: Command failed with exit code 2: make  install-nosysconf
openssh: Compilation error. The package is left as is at /home/username/relocatable-python/parts/openssh__compile__/openssh-5.8p1 where you can inspect what went wrong
While:
  Installing openssh.
Error: System error

**Comment by wiggin15** [comment]
Right, I committed another fix, please try now
