### ISSUE TITLE
RHEL6.4

### ISSUE THREAD

**Issue by amal-khailtash** [Infinidat/relocatable-python#6]
Here is another one I encountered on RHEL6.4:

% ./bin/buildout 
Installing 'zc.buildout', 'setuptools'.
We have the best distribution that satisfies 'zc.buildout>=2.3.1'.
Picked: zc.buildout = 2.3.1
We have the best distribution that satisfies 'setuptools'.
Adding find link 'https://pypi.python.org/packages/source/c/certifi/certifi-1.0.1.tar.gz#md5=45f5cb94b8af9e1df0f9450a8f61b790' from setuptools 14.0
Adding find link 'https://pypi.python.org/packages/source/w/wincertstore/wincertstore-0.2.zip#md5=ae728f2f007185648d0c7a8679b361e2' from setuptools 14.0
Picked: setuptools = 14.0
Develop: '/tools/relocatable-python/.'
/tools/relocatable-python/eggs/setuptools-14.0-py2.6.egg/setuptools/command/egg_info.py:171: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
Installing 'zc.recipe.egg'.
We have no distributions for zc.recipe.egg that satisfies 'zc.recipe.egg>=2.0.0a3'.
Getting distribution for 'zc.recipe.egg>=2.0.0a3'.
Running easy_install:
"/usr/bin/python" "-c" "from setuptools.command.easy_install import main; main()" "-mZUNxd" "/tools/relocatable-python/eggs/tmpR6Tmwr" "-q" "/nfs/projects/centaurfpga/tools/relocatable-python/.cache/dist/zc.recipe.egg-2.0.1.tar.gz"
path=/tools/relocatable-python/eggs/setuptools-14.0-py2.6.egg

While:
  Installing.
  Getting section scripts.
  Initializing section scripts.
  Installing recipe zc.recipe.egg.
  Getting distribution for 'zc.recipe.egg>=2.0.0a3'.
Error: Couldn't install: zc.recipe.egg 2.0.1

**Comment by grzn** [comment]
could you run ```bin/buildout -vvv``` and paste the output?

**Comment by amal-khailtash** [comment]
Here you go:

% ./bin/buildout -vvv
Installing 'zc.buildout', 'setuptools'.
We have the best distribution that satisfies 'zc.buildout>=2.3.1'.
Picked: zc.buildout = 2.3.1
We have the best distribution that satisfies 'setuptools'.
Adding find link 'https://pypi.python.org/packages/source/c/certifi/certifi-1.0.1.tar.gz#md5=45f5cb94b8af9e1df0f9450a8f61b790' from setuptools 14.0
Adding find link 'https://pypi.python.org/packages/source/w/wincertstore/wincertstore-0.2.zip#md5=ae728f2f007185648d0c7a8679b361e2' from setuptools 14.0
Picked: setuptools = 14.0
Develop: '/tools/relocatable-python/.'
in: '/tools/relocatable-python/.'
/usr/bin/python /tmp/tmpjQCita -q develop -mxN -d /tools/relocatable-python/develop-eggs/tmpgop_8Ibuild
/tools/relocatable-python/eggs/setuptools-14.0-py2.6.egg/setuptools/command/egg_info.py:171: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
Installing 'zc.recipe.egg'.
We have no distributions for zc.recipe.egg that satisfies 'zc.recipe.egg>=2.0.0a3'.
Getting distribution for 'zc.recipe.egg>=2.0.0a3'.
Running easy_install:
"/usr/bin/python" "-c" "from setuptools.command.easy_install import main; main()" "-mZUNxd" "/tools/relocatable-python/eggs/tmpFddHxs" "-v" "/tools/relocatable-python/.cache/dist/zc.recipe.egg-2.0.1.tar.gz"
path=/tools/relocatable-python/eggs/setuptools-14.0-py2.6.egg

Processing zc.recipe.egg-2.0.1.tar.gz
Unpacking zc.recipe.egg-2.0.1 to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1
Unpacking zc.recipe.egg-2.0.1/setup.cfg to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/setup.cfg
Unpacking zc.recipe.egg-2.0.1/PKG-INFO to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/PKG-INFO
Unpacking zc.recipe.egg-2.0.1/setup.py to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/setup.py
Unpacking zc.recipe.egg-2.0.1/src to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src
Unpacking zc.recipe.egg-2.0.1/src/zc to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc
Unpacking zc.recipe.egg-2.0.1/src/zc/__init__.py to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc/__init__.py
Unpacking zc.recipe.egg-2.0.1/src/zc/recipe to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc/recipe
Unpacking zc.recipe.egg-2.0.1/src/zc/recipe/egg to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc/recipe/egg
Unpacking zc.recipe.egg-2.0.1/src/zc/recipe/egg/__init__.py to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc/recipe/egg/__init__.py
Unpacking zc.recipe.egg-2.0.1/src/zc/recipe/egg/api.txt to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc/recipe/egg/api.txt
Unpacking zc.recipe.egg-2.0.1/src/zc/recipe/egg/README.txt to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc/recipe/egg/README.txt
Unpacking zc.recipe.egg-2.0.1/src/zc/recipe/egg/custom.py to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc/recipe/egg/custom.py
Unpacking zc.recipe.egg-2.0.1/src/zc/recipe/egg/custom.txt to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc/recipe/egg/custom.txt
Unpacking zc.recipe.egg-2.0.1/src/zc/recipe/egg/tests.py to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc/recipe/egg/tests.py
Unpacking zc.recipe.egg-2.0.1/src/zc/recipe/egg/egg.py to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc/recipe/egg/egg.py
Unpacking zc.recipe.egg-2.0.1/src/zc/recipe/__init__.py to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc/recipe/__init__.py
Unpacking zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info
Unpacking zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info/top_level.txt to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info/top_level.txt
Unpacking zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info/SOURCES.txt to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info/SOURCES.txt
Unpacking zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info/PKG-INFO to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info/PKG-INFO
Unpacking zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info/dependency_links.txt to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info/dependency_links.txt
Unpacking zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info/not-zip-safe to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info/not-zip-safe
Unpacking zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info/namespace_packages.txt to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info/namespace_packages.txt
Unpacking zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info/requires.txt to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info/requires.txt
Unpacking zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info/entry_points.txt to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/src/zc.recipe.egg.egg-info/entry_points.txt
Unpacking zc.recipe.egg-2.0.1/README.txt to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/README.txt
Unpacking zc.recipe.egg-2.0.1/CHANGES.txt to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/CHANGES.txt
Unpacking zc.recipe.egg-2.0.1/MANIFEST.in to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/MANIFEST.in
Reading configuration from /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/setup.cfg
Adding new section [easy_install] to /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/setup.cfg
Writing /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/setup.cfg
Running zc.recipe.egg-2.0.1/setup.py bdist_egg --dist-dir /tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/egg-dist-tmp-o8eWv0
running bdist_egg
running egg_info
writing requirements to src/zc.recipe.egg.egg-info/requires.txt
writing src/zc.recipe.egg.egg-info/PKG-INFO
writing namespace_packages to src/zc.recipe.egg.egg-info/namespace_packages.txt
writing top-level names to src/zc.recipe.egg.egg-info/top_level.txt
writing dependency_links to src/zc.recipe.egg.egg-info/dependency_links.txt
writing entry points to src/zc.recipe.egg.egg-info/entry_points.txt
reading manifest file 'src/zc.recipe.egg.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/zc.recipe.egg.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/zc
copying src/zc/__init__.py -> build/lib/zc
creating build/lib/zc/recipe
copying src/zc/recipe/__init__.py -> build/lib/zc/recipe
creating build/lib/zc/recipe/egg
copying src/zc/recipe/egg/custom.py -> build/lib/zc/recipe/egg
copying src/zc/recipe/egg/tests.py -> build/lib/zc/recipe/egg
copying src/zc/recipe/egg/egg.py -> build/lib/zc/recipe/egg
copying src/zc/recipe/egg/__init__.py -> build/lib/zc/recipe/egg
copying src/zc/recipe/egg/README.txt -> build/lib/zc/recipe/egg
copying src/zc/recipe/egg/api.txt -> build/lib/zc/recipe/egg
copying src/zc/recipe/egg/custom.txt -> build/lib/zc/recipe/egg
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/zc
creating build/bdist.linux-x86_64/egg/zc/recipe
creating build/bdist.linux-x86_64/egg/zc/recipe/egg
copying build/lib/zc/recipe/egg/custom.py -> build/bdist.linux-x86_64/egg/zc/recipe/egg
copying build/lib/zc/recipe/egg/custom.txt -> build/bdist.linux-x86_64/egg/zc/recipe/egg
copying build/lib/zc/recipe/egg/tests.py -> build/bdist.linux-x86_64/egg/zc/recipe/egg
copying build/lib/zc/recipe/egg/egg.py -> build/bdist.linux-x86_64/egg/zc/recipe/egg
copying build/lib/zc/recipe/egg/__init__.py -> build/bdist.linux-x86_64/egg/zc/recipe/egg
copying build/lib/zc/recipe/egg/api.txt -> build/bdist.linux-x86_64/egg/zc/recipe/egg
copying build/lib/zc/recipe/egg/README.txt -> build/bdist.linux-x86_64/egg/zc/recipe/egg
copying build/lib/zc/recipe/__init__.py -> build/bdist.linux-x86_64/egg/zc/recipe
copying build/lib/zc/__init__.py -> build/bdist.linux-x86_64/egg/zc
byte-compiling build/bdist.linux-x86_64/egg/zc/recipe/egg/custom.py to custom.pyc
byte-compiling build/bdist.linux-x86_64/egg/zc/recipe/egg/tests.py to tests.pyc
byte-compiling build/bdist.linux-x86_64/egg/zc/recipe/egg/egg.py to egg.pyc
byte-compiling build/bdist.linux-x86_64/egg/zc/recipe/egg/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/zc/recipe/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/zc/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/zc.recipe.egg.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/zc.recipe.egg.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/zc.recipe.egg.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/zc.recipe.egg.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/zc.recipe.egg.egg-info/namespace_packages.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/zc.recipe.egg.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/zc.recipe.egg.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/zc.recipe.egg.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating '/tmp/easy_install-nECkh_/zc.recipe.egg-2.0.1/egg-dist-tmp-o8eWv0/zc.recipe.egg-2.0.1-py2.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
removing '/home/fpgargrs/.local/lib/python2.6/site-packages/zc.recipe.egg-2.0.1-py2.6.egg' (and everything under it)
creating /home/fpgargrs/.local/lib/python2.6/site-packages/zc.recipe.egg-2.0.1-py2.6.egg
Extracting zc.recipe.egg-2.0.1-py2.6.egg to /home/fpgargrs/.local/lib/python2.6/site-packages
byte-compiling /home/fpgargrs/.local/lib/python2.6/site-packages/zc.recipe.egg-2.0.1-py2.6.egg/zc/__init__.py to __init__.pyc
byte-compiling /home/fpgargrs/.local/lib/python2.6/site-packages/zc.recipe.egg-2.0.1-py2.6.egg/zc/recipe/__init__.py to __init__.pyc
byte-compiling /home/fpgargrs/.local/lib/python2.6/site-packages/zc.recipe.egg-2.0.1-py2.6.egg/zc/recipe/egg/custom.py to custom.pyc
byte-compiling /home/fpgargrs/.local/lib/python2.6/site-packages/zc.recipe.egg-2.0.1-py2.6.egg/zc/recipe/egg/tests.py to tests.pyc
byte-compiling /home/fpgargrs/.local/lib/python2.6/site-packages/zc.recipe.egg-2.0.1-py2.6.egg/zc/recipe/egg/egg.py to egg.pyc
byte-compiling /home/fpgargrs/.local/lib/python2.6/site-packages/zc.recipe.egg-2.0.1-py2.6.egg/zc/recipe/egg/__init__.py to __init__.pyc

Installed /home/fpgargrs/.local/lib/python2.6/site-packages/zc.recipe.egg-2.0.1-py2.6.egg

Because this distribution was installed --multi-version, before you can
import modules from this package in an application, you will need to
'import pkg_resources' and then use a 'require()' call similar to one of
these examples, in order to select the desired version:

    pkg_resources.require("zc.recipe.egg")  # latest installed version
    pkg_resources.require("zc.recipe.egg==2.0.1")  # this exact version
    pkg_resources.require("zc.recipe.egg>=2.0.1")  # this version or higher

Could't load zc.buildout entry point default
from zc.recipe.egg:
Couldn't install: zc.recipe.egg 2.0.1.
While:
  Installing.
  Getting section scripts.
  Initializing section scripts.
  Installing recipe zc.recipe.egg.
  Getting distribution for 'zc.recipe.egg>=2.0.0a3'.
Error: Couldn't install: zc.recipe.egg 2.0.1

Script done on Wed 11 Mar 2015 10:43:09 AM EDT

**Comment by amal-khailtash** [comment]
I guess my /home/fpgargrs/.local/lib/python2.6/ was in the way.  I renamed that and buildout finished.  Not sure if there is a workaround for this.

But I get a different error at the end.

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/multiprocessing/util.py", line 258, in _exit_function
    info('process shutting down')
TypeError: 'NoneType' object is not callable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/multiprocessing/util.py", line 258, in _exit_function
    info('process shutting down')
TypeError: 'NoneType' object is not callable
Got linecache2 1.0.0.
Picked: linecache2 = 1.0.0

**Comment by amal-khailtash** [comment]
% ./bin/build

And build fails:

% ./bin/build
Traceback (most recent call last):
  File "./bin/build", line 24, in <module>
    import scripts
  File "/tools/relocatable-python/src/scripts/__init__.py", line 5, in <module>
    from infi.execute import execute_assert_success
  File "/tools/relocatable-python/eggs/infi.execute-0.1-py2.6.egg/infi/execute/__init__.py", line 3, in <module>
    from .runner import local, through_ssh
  File "/tools/relocatable-python/eggs/infi.execute-0.1-py2.6.egg/infi/execute/runner.py", line 7, in <module>
    from .result import Result
  File "/tools/relocatable-python/eggs/infi.execute-0.1-py2.6.egg/infi/execute/result.py", line 1, in <module>
    from .waiting import wait_for_many_results, flush
  File "/tools/relocatable-python/eggs/infi.execute-0.1-py2.6.egg/infi/execute/waiting.py", line 1, in <module>
    from .ioloop import IOLoop, time
  File "/tools/relocatable-python/eggs/infi.execute-0.1-py2.6.egg/infi/execute/ioloop.py", line 12, in <module>
    from infi.monotonic_time import monotonic_time, is_supported
  File "/tools/relocatable-python/eggs/infi.monotonic_time-0.1.5-py2.6.egg/infi/monotonic_time/__init__.py", line 10, in <module>
    from .linux import monotonic_clock, time_to_monotonic, time_from_monotonic
  File "/tools/relocatable-python/eggs/infi.monotonic_time-0.1.5-py2.6.egg/infi/monotonic_time/linux.py", line 6, in <module>
    from sysconfig import get_config_var
ImportError: No module named sysconfig

**Comment by grzn** [comment]
Well, your system Python is not in great shape... not sure what do you with this...

**Comment by amal-khailtash** [comment]
Yes, these machines are not updated/installed properly!  I will try to switch to another python and report back.  Thanks.

**Comment by grzn** [comment]
so I'm closing the issue for now.
Thanks
