### ISSUE TITLE
Cannot download python sources (Ubuntu)

### ISSUE THREAD

**Issue by amal-khailtash** [Infinidat/relocatable-python#7]
I am past building openssh now and I get this new error:

make[1]: Leaving directory '/home/username/work/relocatable-python/parts/graphviz__compile__/graphviz-2.30.1'
Unused options for graphviz: 'hooks-dir' 'ignore-existing' 'patches-dir'.
Installing python.
python: [ENV] CC = gcc -static-libgcc -fPIC
python: [ENV] CFLAGS = -I/home/username/work/relocatable-python/dist/include -I/home/username/work/relocatable-python/dist/include/gnutls -I/home/username/work/relocatable-python/dist/include/graphviz -I/home/username/work/relocatable-python/dist/include/libexslt -I/home/username/work/relocatable-python/dist/include/libxml2 -I/home/username/work/relocatable-python/dist/include/libxslt -I/home/username/work/relocatable-python/dist/include/ncurses -I/home/username/work/relocatable-python/dist/include/openssl -I/home/username/work/relocatable-python/dist/include/readline -I/home/username/work/relocatable-python/dist/include/sasl -I/home/username/work/relocatable-python/dist/lib/libffi-3.2.1/include
python: [ENV] CPPFLAGS = -I/home/username/work/relocatable-python/dist/include -I/home/username/work/relocatable-python/dist/include/gnutls -I/home/username/work/relocatable-python/dist/include/graphviz -I/home/username/work/relocatable-python/dist/include/libexslt -I/home/username/work/relocatable-python/dist/include/libxml2 -I/home/username/work/relocatable-python/dist/include/libxslt -I/home/username/work/relocatable-python/dist/include/ncurses -I/home/username/work/relocatable-python/dist/include/openssl -I/home/username/work/relocatable-python/dist/include/readline -I/home/username/work/relocatable-python/dist/include/sasl -I/home/username/work/relocatable-python/dist/lib/libffi-3.2.1/include
python: [ENV] DYLD_LIBRARY_PATH = /home/username/work/relocatable-python/dist/lib
python: [ENV] LDFLAGS = -L/home/username/work/relocatable-python/dist/lib -Wl,-rpath,\$$ORIGIN,-rpath,\$$ORIGIN/../lib,-rpath-link,\$$ORIGIN,-rpath-link,\$$ORIGIN/../lib -Wl,-rpath,\$$ORIGIN/../.. -L/home/username/work/relocatable-python/dist/lib/engines -L/home/username/work/relocatable-python/dist/lib/gettext -L/home/username/work/relocatable-python/dist/lib/graphviz -L/home/username/work/relocatable-python/dist/lib/libxslt-plugins -L/home/username/work/relocatable-python/dist/lib/pkgconfig -L/home/username/work/relocatable-python/dist/lib/python2.7 -L/home/username/work/relocatable-python/dist/lib/sasl2
python: [ENV] LD_LIBRARY_PATH = /home/username/work/relocatable-python/dist/lib
python: [ENV] LIBPATH = -L/home/username/work/relocatable-python/dist/lib
python: [ENV] SHARED_LDFLAGS = -L/home/username/work/relocatable-python/dist/lib -Wl,-rpath,\$$ORIGIN,-rpath,\$$ORIGIN/../lib,-rpath-link,\$$ORIGIN,-rpath-link,\$$ORIGIN/../lib
Searching cache at /home/username/work/relocatable-python/.cache/
Cache miss; will cache ftp://python.infinidat.com/python/sources/Python-2.7.8.tgz as /home/username/work/relocatable-python/.cache/018346244fd1b7bdaf8943d5f0f82fb8

Downloading ftp://python.infinidat.com/python/sources/Python-2.7.8.tgz
While:
  Installing python.
Error: Error downloading extends for URL ftp://python.infinidat.com/python/sources/Python-2.7.8.tgz: [Errno ftp error] [Errno ftp error] 550 No such file or directory.

**Comment by wiggin15** [comment]
We just switched to 2.7.8 so the file wasn't synced yet. The file is there now. Thanks.
